# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_sample_project',
                'doc_host': 'https://kurianbenoy.github.io',
                'git_url': 'https://github.com/kurianbenoy/nbdev_sample_project',
                'lib_path': 'nbdev_sample_project'},
  'syms': {'nbdev_sample_project.core': {'nbdev_sample_project.core.foo': ('core.html#foo', 'nbdev_sample_project/core.py')}}}